# Generated by Django 5.1.7 on 2026-04-27 00:50

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('full_name', models.CharField(max_length=250)),
                ('phone', models.CharField(default='9999-9999', max_length=25)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('personal_id', models.CharField(max_length=250)),
                ('id_type', models.CharField(choices=[('cedula', 'Cédula'), ('pasaporte', 'Pasaporte')], max_length=100)),
                ('nac', django_countries.fields.CountryField(max_length=2)),
                ('dob', models.DateField(default='1900-01-01')),
                ('sex', models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer'), ('O', 'Otro')], max_length=100)),
                ('role', models.CharField(choices=[('O', 'Propietario'), ('T', 'Inquilino')], default='T', max_length=100)),
                ('promo_code', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.CharField(max_length=250)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('plan', models.CharField(choices=[('free', 'Gratis/Básico'), ('standard', 'Estándar'), ('enterprise', 'Empresarial')], default='free', max_length=20)),
                ('privacy_policy_accepted', models.BooleanField(default=False, verbose_name='Política de Privacidad Aceptada')),
                ('privacy_policy_accepted_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aceptación de Privacidad')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='Términos y Condiciones Aceptados')),
                ('terms_accepted_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aceptación de Términos')),
                ('marketing_consent', models.BooleanField(default=False, verbose_name='Consentimiento de Marketing')),
                ('data_retention_consent', models.BooleanField(default=True, verbose_name='Consentimiento de Retención de Datos')),
                ('last_privacy_update', models.DateTimeField(auto_now=True, verbose_name='Última Actualización de Privacidad')),
                ('data_deletion_requested', models.BooleanField(default=False, verbose_name='Eliminación de Datos Solicitada')),
                ('data_deletion_request_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Solicitud de Eliminación')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('comment', 'Comentario'), ('feedback', 'Feedback'), ('issue', 'Reportar un problema'), ('suggestion', 'Sugerencia')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('response', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_responses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('apartment', 'Apartamento'), ('house', 'Casa'), ('loft', 'Loft'), ('comercial', 'Local'), ('other', 'Otros')], max_length=100)),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(max_length=250)),
                ('monthly_pmt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('maint_fee', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('maint_status', models.CharField(choices=[('cleared', 'Ninguno'), ('requested', 'Solicitado'), ('asignado', 'Asignado'), ('in_progress', 'En Progreso'), ('finished', 'Terminado')], default='cleared', max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_due_date', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31')], default=1)),
                ('next_invoice_date', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rent_number', models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True)),
                ('rent_sequence_number', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('unregistered_tenant_name', models.CharField(blank=True, max_length=250, null=True)),
                ('unregistered_tenant_email', models.EmailField(blank=True, max_length=250, null=True)),
                ('unregistered_tenant_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('unregistered_tenant_id_type', models.CharField(blank=True, choices=[('cedula', 'Cédula'), ('pasaporte', 'Pasaporte')], max_length=100, null=True)),
                ('unregistered_tenant_personal_id', models.CharField(blank=True, max_length=250, null=True)),
                ('unregistered_tenant_dob', models.DateField(blank=True, null=True)),
                ('unregistered_tenant_nac', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('unregistered_tenant_sex', models.CharField(blank=True, choices=[('M', 'Hombre'), ('F', 'Mujer'), ('O', 'Otro')], max_length=100, null=True)),
                ('late_fee_type', models.CharField(choices=[('none', 'Ninguno'), ('10_percent', '10%'), ('20_percent', '20%'), ('fixed_amount', 'Cantidad Fija')], default='none', max_length=20)),
                ('late_fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('late_fee_grace_days', models.IntegerField(default=5, help_text='Number of days past due before late fee is applied (default: 5)')),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'O'}, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_rents', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.properties')),
                ('tenant', models.ForeignKey(limit_choices_to={'role': 'T'}, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_rents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, help_text='Auto-generated unique invoice identifier', max_length=100, unique=True)),
                ('invoice_date', models.DateField(help_text='Date when invoice was created')),
                ('due_date', models.DateField(help_text='Date when payment is due')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Original rent amount for this invoice', max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid against this invoice', max_digits=10)),
                ('late_fee_amount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Late fee amount (if applicable)', max_digits=10, null=True)),
                ('late_fee_applied_date', models.DateField(blank=True, help_text='Date when late fee was applied', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('partial', 'Parcialmente Pagado'), ('paid', 'Pagado'), ('overdue', 'Vencido'), ('overdue_with_fee', 'Vencido con Recargo')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='main.rent')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Debit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_number', models.CharField(editable=False, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debit_date', models.DateField()),
                ('description', models.TextField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_debits', to=settings.AUTH_USER_MODEL)),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debits', to='main.rent')),
            ],
            options={
                'ordering': ['-debit_date'],
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_number', models.CharField(editable=False, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_date', models.DateField()),
                ('description', models.TextField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_credits', to=settings.AUTH_USER_MODEL)),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='main.rent')),
            ],
            options={
                'ordering': ['-credit_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='main_auditl_user_id_1cd3b6_idx'), models.Index(fields=['action', 'timestamp'], name='main_auditl_action_61f1e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(editable=False, help_text='Auto-generated unique payment identifier', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid', max_digits=10)),
                ('payment_date', models.DateField(help_text='Date when payment was made')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Timestamp when owner confirmed the payment', null=True)),
                ('payment_method', models.CharField(choices=[('ach_yappy', 'ACH o Yappy'), ('cash', 'Efectivo'), ('other', 'Otros')], help_text='How the payment was made', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('rejected', 'Rechazado')], default='pending', max_length=20)),
                ('confirmation_file', models.FileField(blank=True, null=True, upload_to='payment_confirmations/')),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='main.invoice')),
            ],
            options={
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['invoice', 'payment_date'], name='main_paymen_invoice_c56086_idx'), models.Index(fields=['status'], name='main_paymen_status_a07f84_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['rent', 'due_date'], name='main_invoic_rent_id_b2ba9c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='main_invoic_status_1c3a54_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='main_invoic_invoice_d66b1d_idx'),
        ),
    ]
