# Generated by Django 5.1.3 on 2025-04-28 00:48

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('full_name', models.CharField(max_length=250)),
                ('phone', models.CharField(default='9999-9999', max_length=25)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('personal_id', models.CharField(max_length=250)),
                ('id_type', models.CharField(choices=[('cedula', 'Cedula'), ('pasaporte', 'Pasaporte')], max_length=100)),
                ('nac', django_countries.fields.CountryField(max_length=2)),
                ('dob', models.DateField(default='1900-01-01')),
                ('sex', models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer'), ('O', 'Otro')], max_length=100)),
                ('role', models.CharField(choices=[('O', 'Propietario'), ('T', 'Inquilino')], default='propietario', max_length=100)),
                ('username', models.CharField(max_length=250)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('apartment', 'Apartamento'), ('house', 'Casa'), ('loft', 'Loft'), ('comercial', 'Local'), ('other', 'Otros')], max_length=100)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('description', models.TextField(max_length=250)),
                ('monthly_pmt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maint_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maint_status', models.CharField(choices=[('cleared', 'Ninguno'), ('requested', 'Solicitado'), ('asignado', 'Asignado'), ('in_progress', 'En Progreso'), ('finished', 'Terminado')], default='cleared', max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_due_date', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31')], default=5)),
                ('status', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'O'}, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_rents', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.properties')),
                ('tenant', models.ForeignKey(limit_choices_to={'role': 'T'}, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_rents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('credit', 'Credit'), ('debit', 'Debit')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('payment_method', models.CharField(choices=[('ach_yappy', 'ACH O Yappy'), ('cash', 'Efectivo'), ('other', 'Otros')], max_length=100)),
                ('sequence_number', models.PositiveIntegerField(editable=False)),
                ('transaction_number', models.CharField(editable=False, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'O'}, on_delete=django.db.models.deletion.CASCADE, related_name='owner_transactions', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.properties')),
                ('rent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.rent')),
                ('tenant', models.ForeignKey(blank=True, limit_choices_to={'role': 'T'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
