# Generated by Django 5.1.3 on 2025-05-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='next_invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('credit', 'Credit'), ('debit', 'Debit'), ('fee', 'Fee')], max_length=50),
        ),
    ]
