# Generated by Django 5.1.7 on 2026-05-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_confirmed',
            field=models.BooleanField(default=False, verbose_name='Rol Confirmado'),
        ),
    ]
