# Generated by Django 5.1.7 on 2025-05-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_transaction_due_date_transaction_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='rent_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
