# Generated by Django 5.1.7 on 2025-05-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_properties_bathrooms_alter_properties_bedrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='maint_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='monthly_pmt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
