# Generated by Django 5.1.7 on 2025-07-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_properties_maint_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='confirmation_file',
            field=models.FileField(blank=True, null=True, upload_to='payment_confirmations/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('rejected', 'Rechazado')], default='pending', max_length=20),
        ),
    ]
