# Generated by Django 5.1.7 on 2025-08-04 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_transaction_confirmation_file_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
    ]
