# Generated by Django 5.1.7 on 2025-09-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_promocode_user_plan_user_promo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='promo_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
