# Generated by Django 5.1.7 on 2025-09-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_user_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('credit', 'Credit'), ('debit', 'Debit'), ('fee', 'Fee'), ('pago', 'Pago')], max_length=50),
        ),
    ]
