# Generated by Django 5.1.7 on 2025-09-17 01:04

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_user_stripe_customer_id_user_stripe_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='unregistered_tenant_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='unregistered_tenant_email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='unregistered_tenant_id_type',
            field=models.CharField(blank=True, choices=[('cedula', 'Cedula'), ('pasaporte', 'Pasaporte')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='unregistered_tenant_nac',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='unregistered_tenant_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='unregistered_tenant_personal_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='unregistered_tenant_phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='unregistered_tenant_sex',
            field=models.CharField(blank=True, choices=[('M', 'Hombre'), ('F', 'Mujer'), ('O', 'Otro')], max_length=100, null=True),
        ),
    ]
