# Generated by Django 5.1.7 on 2025-11-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rent_unregistered_tenant_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='rent_number',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='rent_sequence_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='unregistered_tenant_id_type',
            field=models.CharField(blank=True, choices=[('cedula', 'Cédula'), ('pasaporte', 'Pasaporte')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('ach_yappy', 'ACH o Yappy'), ('cash', 'Efectivo'), ('other', 'Otros')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('invoice', 'Factura'), ('receipt', 'Recibo'), ('credit', 'Credito'), ('debit', 'Debito'), ('fee', 'Recargo'), ('pago', 'Pago')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_type',
            field=models.CharField(choices=[('cedula', 'Cédula'), ('pasaporte', 'Pasaporte')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('free', 'Gratis/Básico'), ('standard', 'Estándar'), ('enterprise', 'Empresarial')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('O', 'Propietario'), ('T', 'Inquilino')], default='T', max_length=100),
        ),
    ]
