# Generated by Django 5.1.7 on 2025-11-25 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rent_rent_number_rent_rent_sequence_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_deletion_request_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Solicitud de Eliminación'),
        ),
        migrations.AddField(
            model_name='user',
            name='data_deletion_requested',
            field=models.BooleanField(default=False, verbose_name='Eliminación de Datos Solicitada'),
        ),
        migrations.AddField(
            model_name='user',
            name='data_retention_consent',
            field=models.BooleanField(default=True, verbose_name='Consentimiento de Retención de Datos'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_privacy_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización de Privacidad'),
        ),
        migrations.AddField(
            model_name='user',
            name='marketing_consent',
            field=models.BooleanField(default=False, verbose_name='Consentimiento de Marketing'),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_policy_accepted',
            field=models.BooleanField(default=False, verbose_name='Política de Privacidad Aceptada'),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_policy_accepted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aceptación de Privacidad'),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted',
            field=models.BooleanField(default=False, verbose_name='Términos y Condiciones Aceptados'),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aceptación de Términos'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='main_auditl_user_id_1cd3b6_idx'), models.Index(fields=['action', 'timestamp'], name='main_auditl_action_61f1e6_idx')],
            },
        ),
    ]
