# Generated by Django 5.1.7 on 2026-02-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='late_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='late_fee_type',
            field=models.CharField(choices=[('none', 'Ninguno'), ('10_percent', '10%'), ('20_percent', '20%'), ('fixed_amount', 'Cantidad Fija')], default='none', max_length=20),
        ),
    ]
