# Generated by Django 5.1.7 on 2026-02-07 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_invoice_payment_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoice',
            new_name='main_invoic_rent_id_b2ba9c_idx',
            old_name='main_invoice_rent_due_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='main_invoic_status_1c3a54_idx',
            old_name='main_invoice_status_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='main_invoic_invoice_d66b1d_idx',
            old_name='main_invoice_date_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='main_paymen_invoice_c56086_idx',
            old_name='main_payment_invoice_date_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='main_paymen_status_a07f84_idx',
            old_name='main_payment_status_idx',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Original rent amount for this invoice', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(help_text='Date when payment is due'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(help_text='Date when invoice was created'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(editable=False, help_text='Auto-generated unique invoice identifier', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='late_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Late fee amount (if applicable)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='late_fee_applied_date',
            field=models.DateField(blank=True, help_text='Date when late fee was applied', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid against this invoice', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount paid', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(help_text='Date when payment was made'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('ach_yappy', 'ACH o Yappy'), ('cash', 'Efectivo'), ('other', 'Otros')], help_text='How the payment was made', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction',
            field=models.OneToOneField(blank=True, help_text='Original Transaction record for audit trail', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_ref', to='main.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Invoice this transaction is linked to (new workflow)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_transactions', to='main.invoice'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_legacy_only',
            field=models.BooleanField(default=True, help_text='True = old workflow only, False = integrated with new Invoice/Payment system'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment',
            field=models.OneToOneField(blank=True, help_text='Links to new Payment model if created via new workflow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_ref', to='main.payment'),
        ),
    ]
