# Generated by Django 5.1.7 on 2026-02-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_rename_main_invoice_rent_due_idx_main_invoic_rent_id_b2ba9c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when payment was confirmed to prevent duplicate confirmations', null=True),
        ),
    ]
