# Generated by Django 5.1.7 on 2026-03-19 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_transaction_confirmed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='rent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='main.rent'),
        ),
    ]
