# Generated by Django 5.1.3 on 2025-04-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
