# Generated by Django 5.1.3 on 2025-03-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('apartment', 'Apartamento'), ('house', 'Casa'), ('loft', 'Loft'), ('comercial', 'Local'), ('other', 'Otros')], max_length=100)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('description', models.TextField(max_length=250)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_pmt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maint_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_due', models.DateField()),
                ('lease_due', models.DateField()),
                ('lease_dur', models.CharField(choices=[('3', '3 meses'), ('6', '6 meses'), ('12', '12 meses'), ('18', '18 meses'), ('24', '24 meses')], max_length=100)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('no_available', 'No Disponible')], max_length=100)),
                ('maint_status', models.CharField(choices=[('cleared', 'Ninguno'), ('requested', 'Solicitado'), ('asignado', 'Asignado'), ('in_progress', 'En Progreso'), ('finished', 'Terminado')], max_length=100)),
            ],
        ),
    ]
