# Generated by Django 5.1.3 on 2025-04-22 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_properties_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='owner',
            field=models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
