# Generated by Django 5.1.3 on 2025-03-12 23:36

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_properties'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('full_name', models.CharField(max_length=250)),
                ('phone', models.CharField(default='9999-9999', max_length=25)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('personal_id', models.CharField(max_length=250)),
                ('id_type', models.CharField(choices=[('cedula', 'Cedula'), ('pasaporte', 'Pasaporte')], max_length=100)),
                ('nac', django_countries.fields.CountryField(max_length=2)),
                ('dob', models.DateField(default='1900-01-01')),
                ('sex', models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer')], max_length=100)),
            ],
        ),
    ]
