# Generated by Django 5.1.7 on 2025-03-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_properties_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='full_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
