# Generated by Django 5.1.7 on 2025-03-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_tenant_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='full_name',
            field=models.CharField(blank=True, default='<django.db.models.fields.CharField>', max_length=250),
        ),
    ]
