# Generated by Django 5.1.7 on 2025-03-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_tenant_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='personal_id',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
