# Generated by Django 5.1.7 on 2025-03-31 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_tenant_personal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='tenant',
            field=models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tenant'),
        ),
    ]
