# Generated by Django 5.1.7 on 2025-03-31 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_properties_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='tenant',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='main.tenant'),
        ),
    ]
