# Generated by Django 5.1.7 on 2025-04-18 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('ach_yappy', 'ACH O Yappy'), ('cash', 'Efectivo'), ('other', 'Otros')], max_length=100)),
                ('sequence_number', models.PositiveIntegerField()),
                ('invoice_number', models.CharField(editable=False, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_tenant', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tenant')),
                ('to_property', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.properties')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'sequence_number')},
            },
        ),
    ]
